TOKEN_MAP = {
    'IF': 'if',
    'ELSE': 'else',
    'WHILE': 'while',
    'FOR': 'for',
    'RETURN': 'return',
    'DEF': 'def',
    'CLASS': 'class',
    'PRINT': 'print',
    'NONE': 'None',
    'TRUE': 'True',
    'FALSE': 'False',
    'IN': 'in',
    'RANGE': 'range',

    'IDENTIFICADOR': '=',
    'NUMERO': '0',
    'DECIMAL': '0.0',
    'CADENA': '"..."',

    'EQ': '==',
    'NEQ': '!=',
    'LE': '<=',
    'GE': '>=',
    'PLUS_EQ': '+=',
    'MINUS_EQ': '-=',
    'TIMES_EQ': '*=',
    'DIV_EQ': '/=',
    'MOD_EQ': '%=',

    'PLUS': '+',
    'MINUS': '-',
    'TIMES': '*',
    'DIV': '/',
    'MOD': '%',
    'LT': '<',
    'GT': '>',
    'ASIGNACION': '=',

    'LPAREN': '(',
    'RPAREN': ')',
    'LBRACE': '{',
    'RBRACE': '}',
    'LBRACKET': '[',
    'RBRACKET': ']',

    'SEMICOLON': ';',
    'COMMA': ',',
    'COLON': ':'
}
