TOKEN_MAP = {
    'IF': 'if',
    'ELSE': 'else',
    'WHILE': 'while',
    'FOR': 'for',
    'RETURN': 'return',
    'DEF': 'def',
    'CLASS': 'class',
    'PRINT': 'print',
    'NONE': 'None',
    'TRUE': 'True',
    'FALSE': 'False',
    'IN': 'in',
    'RANGE': 'range',

    'identificador': '=',
    'numero': '0',
    'decimal': '0.0',
    'CADENA': '"..."',

    'EQ': '==',
    'NEQ': '!=',
    'LE': '<=',
    'GE': '>=',
    'PLUS_EQ': '+=',
    'MINUS_EQ': '-=',
    'TIMES_EQ': '*=',
    'DIV_EQ': '/=',
    'MOD_EQ': '%=',

    'Operador de suma': '+',
    'Operador de resta': '-',
    'Operador de multiplicacion': '*',
    'Operador de division': '/',
    'MOD': '%',
    'LT': '<',
    'GT': '>',
    'Operador de asignacion': '=',

    'LPAREN': '(',
    'RPAREN': ')',
    'LBRACE': '{',
    'RBRACE': '}',
    'LBRACKET': '[',
    'RBRACKET': ']',

    'Punto y coma': ';',
    'COMMA': ',',
    'COLON': ':',

    # Nuevos tokens compatibles con hard.yalp
    'PalabraClave_IF': 'if',
    'PalabraClave_WHILE': 'while',
    'PalabraClave_FOR': 'for',
    'PalabraClave_RETURN': 'return',
    'PalabraClave_IN': 'in',

    'Identificador': '=',
    'Numero': '0',
    'Decimal': '0.0',
    'cadena': '"..."',

    'Operador_de_igualdad': '==',
    'Operador_diferente': '!=',
    'Operador_menor_igual': '<=',
    'Operador_mayor_igual': '>=',
    'Operador_de_suma': '+',
    'Operador_de_resta': '-',
    'Operador_de_multiplicacion': '*',
    'Operador_de_division': '/',
    'Operador_de_modulo': '%',
    'Operador_menor_que': '<',
    'Operador_mayor_que': '>',
    'Operador_de_asignacion': '=',

    'Parentesis_izquierdo': '(',
    'Parentesis_derecho': ')',
    'Llave_izquierda': '{',
    'Llave_derecha': '}',
    'Corchete_izquierdo': '[',
    'Corchete_derecho': ']',
    'Punto_y_coma': ';',
    'Coma': ',',
    'Dos_puntos': ':'
}